# Generated by Django 6.0.7 on 2026-07-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('design', 'Design'), ('tools', 'Tools')], max_length=20)),
                ('proficiency', models.IntegerField(default=0, help_text='0-100, used for progress bar width')),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='skills/')),
                ('is_tool', models.BooleanField(default=False, help_text='Split skills vs tools sections')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers show first')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
